#!/usr/bin/env python
import os

godot_cpp_path = ARGUMENTS.get("godot_cpp_path", "../../../../godot-cpp")

env = SConscript(godot_cpp_path + "/SConstruct")

env.Append(CPPPATH=["src/", "../chunk_executables/"])

sources = Glob("src/*.cpp") + [
    "../chunk_executables/generation_test_planet.c",
    "../chunk_executables/fnl.c",
    "../chunk_executables/constants.c",
]

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/libchunkserver.{}.{}.framework/libchunkserver.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/libchunkserver{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
